// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {context} from '../models';

export function CancelPrompt(arg1:string,arg2:string):Promise<void>;

export function CloseEmbeddedTerminal(arg1:string):Promise<void>;

export function ConnectAgent(arg1:string,arg2:string):Promise<string>;

export function CreateEmbeddedTerminal(arg1:string):Promise<backend.EmbeddedTerminalInfo>;

export function DisconnectAgent(arg1:string):Promise<void>;

export function GetSessionAccessModes(arg1:string):Promise<backend.SessionModesInfo>;

export function GetSessionHistory(arg1:string):Promise<backend.SessionHistoryInfo>;

export function GetSessionModels(arg1:string):Promise<backend.SessionModelsInfo>;

export function GetSessionModes(arg1:string):Promise<backend.SessionModesInfo>;

export function GetSettings():Promise<backend.AppSettingsInfo>;

export function ListAvailableAgents():Promise<Array<backend.AgentInfo>>;

export function ListConnections():Promise<Array<backend.ConnectionInfo>>;

export function ListFiles(arg1:string):Promise<Array<backend.FileEntry>>;

export function ListInstalledAgents():Promise<Array<backend.AgentInfo>>;

export function ListRemoteSessions(arg1:string,arg2:string,arg3:string):Promise<backend.SessionListPage>;

export function ListSessions():Promise<Array<backend.SessionListItem>>;

export function LoadRemoteSession(arg1:string,arg2:string,arg3:string):Promise<void>;

export function NewSession(arg1:string,arg2:string):Promise<string>;

export function RejectQuestion(arg1:string):Promise<void>;

export function ResizeEmbeddedTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RespondPermission(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RespondQuestion(arg1:string,arg2:Record<string, Array<string>>):Promise<void>;

export function ResumeHistoricalSession(arg1:string):Promise<backend.ResumeHistoricalResult>;

export function ResumeSession(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveSettings(arg1:backend.AppSettingsInfo):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SendPrompt(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetSessionAccessMode(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetSessionConfigOption(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetSessionMode(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetSessionModel(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function WriteEmbeddedTerminal(arg1:string,arg2:string):Promise<void>;
