// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelPrompt(arg1:string,arg2:string):Promise<void>;

export function ConnectAgent(arg1:string,arg2:string):Promise<string>;

export function DisconnectAgent(arg1:string):Promise<void>;

export function GetSessionHistory(arg1:string):Promise<main.SessionHistoryInfo>;

export function GetSettings():Promise<main.AppSettingsInfo>;

export function ListAvailableAgents():Promise<Array<main.AgentInfo>>;

export function ListConnections():Promise<Array<main.ConnectionInfo>>;

export function ListFiles(arg1:string):Promise<Array<main.FileEntry>>;

export function ListInstalledAgents():Promise<Array<main.AgentInfo>>;

export function ListSessions():Promise<Array<main.SessionListItem>>;

export function NewSession(arg1:string,arg2:string):Promise<string>;

export function RespondPermission(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:main.AppSettingsInfo):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SendPrompt(arg1:string,arg2:string,arg3:string):Promise<void>;
