// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelPrompt(arg1, arg2) {
  return window['go']['main']['App']['CancelPrompt'](arg1, arg2);
}

export function CloseEmbeddedTerminal(arg1) {
  return window['go']['main']['App']['CloseEmbeddedTerminal'](arg1);
}

export function ConnectAgent(arg1, arg2) {
  return window['go']['main']['App']['ConnectAgent'](arg1, arg2);
}

export function CreateEmbeddedTerminal(arg1) {
  return window['go']['main']['App']['CreateEmbeddedTerminal'](arg1);
}

export function DisconnectAgent(arg1) {
  return window['go']['main']['App']['DisconnectAgent'](arg1);
}

export function GetSessionHistory(arg1) {
  return window['go']['main']['App']['GetSessionHistory'](arg1);
}

export function GetSessionModels(arg1) {
  return window['go']['main']['App']['GetSessionModels'](arg1);
}

export function GetSessionModes(arg1) {
  return window['go']['main']['App']['GetSessionModes'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListAvailableAgents() {
  return window['go']['main']['App']['ListAvailableAgents']();
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function ListInstalledAgents() {
  return window['go']['main']['App']['ListInstalledAgents']();
}

export function ListRemoteSessions(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListRemoteSessions'](arg1, arg2, arg3);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LoadRemoteSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoadRemoteSession'](arg1, arg2, arg3);
}

export function NewSession(arg1, arg2) {
  return window['go']['main']['App']['NewSession'](arg1, arg2);
}

export function ResizeEmbeddedTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeEmbeddedTerminal'](arg1, arg2, arg3);
}

export function RespondPermission(arg1, arg2, arg3) {
  return window['go']['main']['App']['RespondPermission'](arg1, arg2, arg3);
}

export function ResumeHistoricalSession(arg1) {
  return window['go']['main']['App']['ResumeHistoricalSession'](arg1);
}

export function ResumeSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResumeSession'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SendPrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendPrompt'](arg1, arg2, arg3);
}

export function SetSessionConfigOption(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetSessionConfigOption'](arg1, arg2, arg3, arg4);
}

export function SetSessionMode(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSessionMode'](arg1, arg2, arg3);
}

export function SetSessionModel(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSessionModel'](arg1, arg2, arg3);
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function WriteEmbeddedTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteEmbeddedTerminal'](arg1, arg2);
}
