// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelPrompt(arg1, arg2) {
  return window['go']['main']['App']['CancelPrompt'](arg1, arg2);
}

export function ConnectAgent(arg1, arg2) {
  return window['go']['main']['App']['ConnectAgent'](arg1, arg2);
}

export function DisconnectAgent(arg1) {
  return window['go']['main']['App']['DisconnectAgent'](arg1);
}

export function GetSessionHistory(arg1) {
  return window['go']['main']['App']['GetSessionHistory'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListAvailableAgents() {
  return window['go']['main']['App']['ListAvailableAgents']();
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function ListInstalledAgents() {
  return window['go']['main']['App']['ListInstalledAgents']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function NewSession(arg1, arg2) {
  return window['go']['main']['App']['NewSession'](arg1, arg2);
}

export function RespondPermission(arg1, arg2) {
  return window['go']['main']['App']['RespondPermission'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SendPrompt(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendPrompt'](arg1, arg2, arg3);
}
